version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "weekly" }
    open-pull-requests-limit: 10
    groups:
      eslint-prettier:
        patterns: ["eslint*", "prettier*"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
